# Generated by Django 5.0.1 on 2024-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='no img.jpg', upload_to='images/'),
        ),
    ]
