# Generated by Django 5.0.1 on 2024-02-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('esalary', models.FloatField()),
            ],
        ),
    ]
